config/routes.rb
Boxroom::Application.routes.draw do
  get '/file_exists', :to => 'files#exists'
  get '/signin', :to => 'sessions#new', :as => 'signin'
  delete '/signout', :to => 'sessions#destroy'

  # Resources
  resources :admins, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :reset_password, :except => [:index, :show, :destroy]
  resources :signup, :only => [:edit, :update]
  resources :groups, :except => :show
  resources :files, :except => [:index, :new, :create]
  resources :share_links, :only => [:index, :show, :destroy]

  resources :users, :except => :show do
    put :extend, :on => :member
  end

  resources :clipboard, :only => [:create, :destroy] do
    post :copy, :on => :member
    post :move, :on => :member
    put :reset, :on => :member
  end

  # Update a collection of permissions
  resources :permissions, :only => :update_multiple do
    put :update_multiple, :on => :collection
  end

  # Nested resources
  resources :folders, :shallow => true, :except => [:new, :create] do
    resources :folders, :only => [:new, :create]
    resources :files, :only => [:new, :create]
  end

  resources :files, :shallow => :true, :only => :show do
    resources :share_links, :only => [:new, :create]
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "folders#index"
end

app/views/shared/_footer.html.erb
<div id="footer">
  <p class="footer">
    <a href="http://boxroomapp.com/">Boxroom</a> is released under the <a href="http://boxroomapp.com/license">MIT license</a>
  </p>
</div>

app/views/shared/_header.html.erb
<div id="header">
  <% if signed_in? -%>
  <div class="user_welcome">
    <p>
      <%= t :hello %>, <%= current_user.name %>!<br>
      <%= link_to t(:settings), edit_user_path(current_user) %> | <%= link_to t(:sign_out), signout_path, :method => :delete %>
    </p>
  </div>
  <% end -%>
  <%= link_to image_tag('logo.png', :alt => 'Boxroom'), root_path %>
</div>

app/views/shared/_menu.html.erb
<div id="menu">
  <p class="menu">
  <% if signed_in? -%>
    <%= link_to t(:folders), folders_path %> &nbsp; &nbsp;
  <% if current_user.member_of_admins? -%>
    <%= link_to t(:users), users_path %> &nbsp; &nbsp;
    <%= link_to t(:groups), groups_path %> &nbsp; &nbsp;
    <%= link_to t(:shared_files), share_links_path %>
  <% end -%>
  <% end -%>
    &nbsp;
  </p>
</div>